# Generated by Django 4.1.2 on 2023-05-12 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_operacion_cant_pasajeros_operacion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='clients.mecanico'),
        ),
    ]
