# Generated by Django 4.1.2 on 2023-05-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_operacion_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='horas_inspecciones_varias_100',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='horas_inspecciones_varias_25',
            field=models.FloatField(blank=True, default=25.0, null=True),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='horas_inspecciones_varias_50',
            field=models.FloatField(blank=True, default=50.0, null=True),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='vencimiento_anexo_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='vencimiento_inspeccion_anual',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='vencimiento_notaciones_requerimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
