# Generated by Django 4.1.2 on 2023-05-15 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0014_aeronave_horas_inspecciones_varias_100_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
