# Generated by Django 4.1.2 on 2023-02-10 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Mechanics',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Operators',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Reasons',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('alumn', models.CharField(blank=True, max_length=100)),
                ('fuel', models.IntegerField(max_length=50)),
                ('takeoff_place', models.CharField(max_length=100)),
                ('landing_place', models.CharField(max_length=100)),
                ('engine_ignition_1', models.TimeField()),
                ('engine_ignition_2', models.TimeField()),
                ('takeoff_time', models.TimeField()),
                ('landing_time', models.TimeField()),
                ('engine_cut_1', models.TimeField()),
                ('engine_cut_2', models.TimeField()),
                ('number_of_landings', models.IntegerField(max_length=100)),
                ('number_of_splashdowns', models.IntegerField(max_length=100)),
                ('start_up_cycles', models.IntegerField(max_length=100)),
                ('fuel_on_landing', models.IntegerField(max_length=100)),
                ('fuel_per_flight', models.IntegerField(max_length=100)),
                ('water_release_cycles', models.IntegerField(max_length=100)),
                ('water_release_amount', models.IntegerField(max_length=100)),
                ('cycles_with_external_load', models.IntegerField(max_length=100)),
                ('weight_with_external_load', models.IntegerField(max_length=100)),
                ('other_reason', models.CharField(blank=True, max_length=100)),
                ('loaded_fuel', models.IntegerField(max_length=100)),
                ('operation_note', models.TextField(blank=True)),
                ('maintenance_note', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clients.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clients.client')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clients.mechanic')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clients.operator')),
                ('reason_of_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clients.reason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
