# Generated by Django 4.1.2 on 2023-02-18 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expiration', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='expiration',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
