# Generated by Django 4.1.2 on 2023-03-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='subtotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gasto',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100),
        ),
    ]
