# Generated by Django 4.1.2 on 2023-03-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='used_fuel',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
