# Generated by Django 4.1.2 on 2023-04-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='horas_voladas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='horas_disponibles',
            field=models.FloatField(),
        ),
    ]
