# Generated by Django 4.1.2 on 2023-03-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_gasto_subtotal_alter_gasto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='porcentaje',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
