# Generated by Django 4.1.2 on 2023-04-11 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_aeronave_horas_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
