# Generated by Django 4.1.2 on 2023-04-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_operacion_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('horas_voladas', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Otros',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='piloto',
            name='horas_voladas',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
