# Generated by Django 4.1.2 on 2023-05-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_operacion_alumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='engine_cut_2',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='engine_ignition_2',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='total_encendido_2',
        ),
        migrations.AddField(
            model_name='operacion',
            name='total_ciclos_encendido',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='operacion',
            name='total_horas_aeronave',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='operacion',
            name='total_horas_alumn',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='operacion',
            name='total_horas_disponibles_aeronave',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='operacion',
            name='total_horas_piloto',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
