# Generated by Django 4.1.2 on 2023-05-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_conceptonograbado_impuestovario_iva_moneda_traslado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='cant_pasajeros',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
