# Generated by Django 4.1.2 on 2023-05-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_aeronave_aterrizajes_operacion_total_aterrizajes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronave',
            name='horas_disponibles',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='horas_inspecciones_varias_100',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='horas_inspecciones_varias_25',
            field=models.DecimalField(blank=True, decimal_places=2, default=25.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='horas_inspecciones_varias_50',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='horas_voladas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='total_horas_aeronave',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='total_horas_alumn',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='total_horas_disponibles_aeronave',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='total_horas_piloto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otro',
            name='horas_voladas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='horas_voladas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
