# Generated by Django 4.1.2 on 2023-04-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_aeronave_ciclos_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronave',
            name='horas_disponibles',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
