# Generated by Django 4.1.2 on 2023-04-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_otro_piloto_horas_voladas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'ordering': ('title',),
            },
        ),
        migrations.AlterModelOptions(
            name='operacion',
            options={'verbose_name_plural': 'Operaciones'},
        ),
        migrations.AddField(
            model_name='otro',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.rol'),
        ),
    ]
